// RwMaxGroup.h: interface for the RwMaxGroup class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_RWMAXGROUP_H__E396CD74_01AF_48D2_AB3C_634ECB4CD7D2__INCLUDED_)
#define AFX_RWMAXGROUP_H__E396CD74_01AF_48D2_AB3C_634ECB4CD7D2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "stdafx.h"

#include "RwCommTransform.h"
#include "RwCommObjCreator.h"

class MaxSimpleTransform  : public RwCommTransform
{
public:
	MaxSimpleTransform(INode*);
	virtual ~MaxSimpleTransform();

    // Destroy the object - called by RwCommObject::Release()
    virtual void Destroy() { delete this; }

	// Matrix querys
	virtual RwCommError	    GetObjMatrix(RwCommMatrix& matrix) const;
	virtual RwCommError 	GetWorldMatrix(RwCommMatrix& matrix) const;

    // Visibility
    virtual RwCommError     GetVisibility(bool& bIsVisible) const;

    // Axis system
    virtual RwCommError 	GetAxisSystem(RwCommMatrix& matrix) const { return RWCOMM_NOT_IMPLEMENTED; }

    // User Data
    virtual RwCommError     GetUserData(RwCommUserDataCollection &userDataColl) { return RWCOMM_NOT_IMPLEMENTED; }
    
    // Get attribute methods.
    virtual RwCommError GetAttribute(const string& name, int &value, int index = 0) { return RWCOMM_NOT_IMPLEMENTED; }
    virtual RwCommError GetAttribute(const string& name, float &value, int index = 0) { return RWCOMM_NOT_IMPLEMENTED; }
    virtual RwCommError GetAttribute(const string& name, string &value, int index = 0) { return RWCOMM_NOT_IMPLEMENTED; }
    virtual RwCommError GetAttributeNames(vector<string>& vAttributeNames, vector<AttributeType> &vAttributeTypes) { return RWCOMM_NOT_IMPLEMENTED; }

    virtual RwCommError     GetNodeTagValue(int &tagValue, bool &bAutoGenerated) const { return RWCOMM_NOT_IMPLEMENTED; }

protected:

    RwCommMatrix Mat3ToRwCommMatrix(const Matrix3& m) const;

protected:

    INode*  m_pNode;

};


class MaxSimpleTransformCreator  : public RwCommObjCreator
{
public:
	MaxSimpleTransformCreator();
	virtual ~MaxSimpleTransformCreator();

	virtual RwCommObject* Create(const RwCommCreationData* pCreationData,
								const RwCommExportOptions* pExportOptions) const;

	virtual void Init(	RwCommObject* pObject,
						const RwCommCreationData* pCreationData,
						const RwCommExportOptions* pExportOptions) const;

	virtual void Attach(RwCommObject* pObject, RwCommObject* pParent, RwCommScene* pScene,
                        const RwCommCreationData* pCreationData) const;
};

#endif // !defined(AFX_RWMAXGROUP_H__E396CD74_01AF_48D2_AB3C_634ECB4CD7D2__INCLUDED_)
